kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-role-aggr
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.rciots.com/aggregate-to-test-role-aggr: 'true'